import base from './worker.js';

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"};
const BOT_USERNAME='BrandHunterMaysterBot';
const BOT_URL=`https://t.me/${BOT_USERNAME}`;
const LEGAL_GATE_VERSION='1.1';
const FINAL_LABEL='TECHNICAL PASS';
const DEFAULT_BRIEF={title:'VYTA replacement',examples:'',meaning:'life, health, personal intelligence, guidance',style:'short, premium, warm, global, easy to pronounce',avoid:'VITA, VYTA, VIA, pharma feel, human-name feel',minLength:5,maxLength:9};

function timeoutSignal(ms){return AbortSignal.timeout?AbortSignal.timeout(ms):undefined}
function ddgQuery(q){return`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`}
async function fetchText(url,ms=7000){try{const r=await fetch(url,{signal:timeoutSignal(ms),redirect:'follow'});if(!r.ok)return{ok:false,status:r.status,text:''};return{ok:true,status:r.status,text:(await r.text()).slice(0,300000)}}catch(e){return{ok:false,status:0,text:'',error:String(e?.message||e)}}}
async function searchSignal(name,query){const r=await fetchText(ddgQuery(query));if(!r.ok)return{available:false,hits:0,reason:`search unavailable (${r.status||'network'})`};const html=r.text.toLowerCase(),n=name.toLowerCase(),cards=(html.match(/result__a/g)||[]).length,mentions=Math.max(0,html.split(n).length-1);return{available:true,hits:Math.min(15,cards)+Math.min(15,mentions)}}
async function domainRegistered(domain){try{const r=await fetch(`https://rdap.org/domain/${encodeURIComponent(domain)}`,{headers:{accept:'application/rdap+json,application/json'},signal:timeoutSignal(6000),redirect:'follow'});if(r.status===404)return{available:true,registered:false};if(r.ok)return{available:true,registered:true}}catch{}return{available:false,registered:null}}
async function domainGate(name){const b=name.toLowerCase(),tlds=['com','ai','app','health','care','io'];const results=await Promise.all(tlds.map(async tld=>{const domain=`${b}.${tld}`;return{domain,...await domainRegistered(domain)}}));return{available:results.some(x=>x.available),registered:results.filter(x=>x.registered===true).length,results}}
async function appleGate(name){try{const r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(name)}&entity=software&limit=50`,{signal:timeoutSignal(7000)});if(!r.ok)return{available:false,exact:0,near:0};const j=await r.json(),n=name.toLowerCase(),rows=j.results||[],exact=rows.filter(x=>String(x.trackName||'').toLowerCase()===n||String(x.sellerName||'').toLowerCase()===n).length,near=rows.filter(x=>String(x.trackName||'').toLowerCase().includes(n)||n.includes(String(x.trackName||'').toLowerCase())).length;return{available:true,exact,near}}catch{return{available:false,exact:0,near:0}}}
function phoneticForms(name){const n=String(name||'').toUpperCase().replace(/[^A-Z]/g,''),s=n.replace(/[AEIOUY]/g,'').replace(/(.)\1+/g,'$1'),v=n.replace(/[AEIOUY]+/g,'*');return[...new Set([n,s,v].filter(x=>x.length>=3))]}
async function legalRiskGate(env,candidate){const name=String(candidate?.name||'').trim().toUpperCase();if(!name)return{status:'BLOCK',reason:'invalid_name',version:LEGAL_GATE_VERSION};const cached=env.AUTOPILOT_KV?await env.AUTOPILOT_KV.get(`legal_gate:${name}`):null;if(cached){try{return JSON.parse(cached)}catch{}}
 const q=`"${name}"`,forms=phoneticForms(name),similarQuery=forms.map(x=>`"${x}"`).join(' OR ');const [exact,health,software,play,euipo,wipo,tmview,classes,similar,apple,domains]=await Promise.all([searchSignal(name,q),searchSignal(name,`${q} health wellness nutrition fitness medical healthcare`),searchSignal(name,`${q} software app AI SaaS company startup`),searchSignal(name,`site:play.google.com ${q}`),searchSignal(name,`site:euipo.europa.eu ${q}`),searchSignal(name,`site:wipo.int ${q}`),searchSignal(name,`site:tmview.org ${q}`),searchSignal(name,`${q} trademark class 9 35 41 42 44 software health`),searchSignal(name,`${similarQuery} brand trademark company app health software`),appleGate(name),domainGate(name)]);const checks={exact,health,software,play,euipo,wipo,tmview,classes,similar,apple,domains},unknown=Object.values(checks).filter(x=>x&&x.available===false).length,tmHits=[euipo,wipo,tmview].reduce((s,x)=>s+(x.available?x.hits:0),0);let risk=0;risk+=Math.min(30,(exact.hits||0)*3)+Math.min(18,(health.hits||0)*2)+Math.min(16,(software.hits||0)*2)+Math.min(15,(play.hits||0)*3)+Math.min(35,tmHits*6)+Math.min(12,(classes.hits||0)*2)+Math.min(18,(similar.hits||0))+Math.min(18,(apple.exact||0)*8+(apple.near||0)*2)+Math.min(12,(domains.registered||0)*2);risk=Math.min(100,risk);let status='LEGAL_REVIEW';const reasons=[];if(tmHits>=2){status='BLOCK';reasons.push('trademark signals')}if((apple.exact||0)>0){status='BLOCK';reasons.push('exact App Store match')}if((exact.hits||0)>=8){status='BLOCK';reasons.push('strong exact public presence')}if(risk>=58){status='BLOCK';reasons.push('aggregate risk too high')}if(status!=='BLOCK'&&unknown===0&&risk<=10&&tmHits===0&&(apple.exact||0)===0&&(exact.hits||0)<=2&&(health.hits||0)<=2&&(software.hits||0)<=2&&(play.hits||0)<=1&&(similar.hits||0)<=4)status=FINAL_LABEL;if(status==='LEGAL_REVIEW'&&!reasons.length){if(unknown>0)reasons.push('incomplete public data');if(risk>10)reasons.push('non-zero similarity/public signals')}const result={name,status,riskScore:risk,unknownChecks:unknown,trademarkHits:tmHits,checkedAt:new Date().toISOString(),version:LEGAL_GATE_VERSION,reasons,checks,disclaimer:'Automated public-signal screening only. TECHNICAL PASS is not legal trademark clearance.'};if(env.AUTOPILOT_KV)await env.AUTOPILOT_KV.put(`legal_gate:${name}`,JSON.stringify(result),{expirationTtl:604800});return result}

async function telegramApi(env,method,payload){if(!env.TELEGRAM_BOT_TOKEN)return{ok:false,error:'TELEGRAM_BOT_TOKEN missing'};try{const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload||{}),signal:timeoutSignal(8000)}),data=await r.json().catch(()=>({}));return{ok:r.ok&&data.ok===true,status:r.status,data,error:data?.description||(!r.ok?`HTTP ${r.status}`:undefined)}}catch(e){return{ok:false,error:String(e?.message||e)}}}
async function getTelegramChat(env){if(!env.AUTOPILOT_KV)return null;const raw=await env.AUTOPILOT_KV.get('telegram_chat');if(!raw)return null;try{return JSON.parse(raw)}catch{return null}}
async function discoverTelegramChat(env){if(!env.AUTOPILOT_KV)return{ok:false,error:'AUTOPILOT_KV missing'};const r=await telegramApi(env,'getUpdates',{limit:100,timeout:0,allowed_updates:['message']});if(!r.ok)return r;const updates=Array.isArray(r.data?.result)?r.data.result:[],messages=updates.map(x=>x?.message).filter(Boolean).filter(m=>m?.chat?.id);if(!messages.length)return{ok:false,error:'no_messages'};const preferred=[...messages].reverse().find(m=>String(m.text||'').trim().toLowerCase().startsWith('/start'))||messages[messages.length-1],chat={id:String(preferred.chat.id),firstName:preferred.chat.first_name||'',username:preferred.chat.username||'',connectedAt:new Date().toISOString()};await env.AUTOPILOT_KV.put('telegram_chat',JSON.stringify(chat));return{ok:true,chat}}
async function sendTelegram(env,text){const chat=await getTelegramChat(env);if(!chat?.id)return{ok:false,error:'chat_not_connected'};return telegramApi(env,'sendMessage',{chat_id:chat.id,text,disable_web_page_preview:true,reply_markup:{inline_keyboard:[[{text:'Открыть Brand Hunter',url:'https://brand-hunter.maysterww.workers.dev/autopilot.html'}]]}})}
async function handleTelegram(request,env){if(!env.AUTOPILOT_KV)return Response.json({ok:false,error:'AUTOPILOT_KV not configured'},{status:503,headers:JSON_HEADERS});const connected=await getTelegramChat(env);if(request.method==='GET')return Response.json({ok:true,tokenConfigured:!!env.TELEGRAM_BOT_TOKEN,connected:!!connected?.id,chat:connected?{firstName:connected.firstName,username:connected.username}:null,botUrl:BOT_URL,botUsername:BOT_USERNAME,legalGateVersion:LEGAL_GATE_VERSION},{headers:JSON_HEADERS});if(request.method!=='POST')return Response.json({ok:false,error:'GET or POST required'},{status:405,headers:JSON_HEADERS});let body={};try{body=await request.json()}catch{}if((body.action||'connect')==='connect'){const d=await discoverTelegramChat(env);if(!d.ok)return Response.json({...d,botUrl:BOT_URL},{status:400,headers:JSON_HEADERS});const welcome=await sendTelegram(env,'✅ Brand Hunter UNIVERSAL AUTOPILOT подключён. Поиск будет идти по твоему сохранённому заданию; уведомление — только при TECHNICAL PASS.');return Response.json({ok:true,connected:true,botUrl:BOT_URL,delivery:welcome},{headers:JSON_HEADERS})}if(body.action==='test'){const sent=await sendTelegram(env,'✅ TEST: Telegram работает. Universal Autopilot использует твоё поисковое задание и пишет только при TECHNICAL PASS.');return Response.json({ok:sent.ok,connected:sent.ok,botUrl:BOT_URL,delivery:sent},{status:sent.ok?200:400,headers:JSON_HEADERS})}return Response.json({ok:false,error:'unknown action'},{status:400,headers:JSON_HEADERS})}

function clean(v,max=500){return String(v||'').trim().slice(0,max)}
function normalizeBrief(b){return{title:clean(b?.title||DEFAULT_BRIEF.title,80),examples:clean(b?.examples,500),meaning:clean(b?.meaning||DEFAULT_BRIEF.meaning,500),style:clean(b?.style||DEFAULT_BRIEF.style,300),avoid:clean(b?.avoid||DEFAULT_BRIEF.avoid,400),minLength:Math.max(4,Math.min(10,Number(b?.minLength)||5)),maxLength:Math.max(5,Math.min(12,Number(b?.maxLength)||9)),updatedAt:new Date().toISOString()}}
async function getBrief(env){if(!env.AUTOPILOT_KV)return DEFAULT_BRIEF;const raw=await env.AUTOPILOT_KV.get('naming_brief');if(!raw)return DEFAULT_BRIEF;try{return{...DEFAULT_BRIEF,...JSON.parse(raw)}}catch{return DEFAULT_BRIEF}}
async function handleBrief(request,env){if(!env.AUTOPILOT_KV)return Response.json({ok:false,error:'AUTOPILOT_KV not configured'},{status:503,headers:JSON_HEADERS});if(request.method==='GET')return Response.json({ok:true,brief:await getBrief(env)},{headers:JSON_HEADERS});if(request.method!=='POST')return Response.json({ok:false,error:'GET or POST required'},{status:405,headers:JSON_HEADERS});let b={};try{b=await request.json()}catch{}const brief=normalizeBrief(b);await env.AUTOPILOT_KV.put('naming_brief',JSON.stringify(brief));return Response.json({ok:true,brief},{headers:JSON_HEADERS})}

const PFX=['AL','AR','AV','EL','EN','ER','EV','IL','IN','IR','LA','LE','LO','MA','ME','MI','NA','NE','NO','OR','RA','RE','SA','SE','TA','TE','VA','VE','VI','VO','SY','LY','AY'];
const MID=['L','M','N','R','S','T','V','D','LOR','REN','VEL','MAR','NEL','RIN','SOR','TAR','VEN','MER','LIS','NOR','VAR','SEL','NEX','LYN','ORA','LUM','SEN','NAV','VER','COR'];
const END=['A','O','I','E','EN','EL','ER','IS','ON','OR','IO','IA','EO','AR','IN','OS','YA','UM','IX','YS'];
const SEM={life:['LIV','VIV','ELA','ZIV'],health:['SAL','SAN','VIG'],wellness:['SAL','VEL','VIV'],path:['NAV','ITER','TRA'],journey:['ITER','NAV','ORA'],guide:['NAV','ORA','LUM'],guidance:['NAV','ORA','LUM'],intelligence:['SEN','LUM','NEX'],smart:['SEN','NEX','LUM'],mind:['SEN','MENT','NOO'],care:['CURA','CAR','VEL'],trust:['VER','FID'],energy:['VIG','ELA','ELAN'],balance:['EQU','BAL','HARM'],clarity:['LUM','VER','SEN'],personal:['UNI','MY','ONA'],жизнь:['LIV','VIV','ELA','ZIV'],здоровье:['SAL','SAN','VIG'],путь:['NAV','ITER','TRA'],навигация:['NAV','ORA'],ум:['SEN','LUM','NEX'],интеллект:['SEN','NEX','LUM'],забота:['CURA','CAR','VEL'],энергия:['VIG','ELA','ELAN'],доверие:['VER','FID'],баланс:['BAL','HARM','EQU'],ясность:['LUM','VER','SEN'],життя:['LIV','ZIV','ELA'],здоровя:['SAL','SAN'],шлях:['NAV','ITER'],розум:['SEN','NEX'],energie:['VIG','ELA'],zivot:['ZIV','LIV'],zdravi:['SAL','SAN']};
function words(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').split(/[^a-zа-яіїєё0-9]+/i).filter(Boolean)}
function asciiExamples(s){return String(s||'').toUpperCase().split(/[\s,;|/]+/).map(x=>x.replace(/[^A-Z]/g,'')).filter(x=>x.length>=3&&x.length<=14)}
function rootsFromBrief(b){const roots=[];for(const w of words(`${b.meaning} ${b.style}`)){if(SEM[w])roots.push(...SEM[w])}for(const ex of asciiExamples(b.examples)){if(ex.length>=4){roots.push(ex.slice(0,3),ex.slice(-3));if(ex.length>=6)roots.push(ex.slice(1,4))}}return[...new Set(roots.filter(x=>x.length>=2&&x.length<=5))]}
function avoidList(b){return[...new Set(['VITA','VYTA','VIA','VITAVIA','VYTAVIA',...asciiExamples(b.avoid)])]}
function hash(n){return[...n].reduce((a,x,i)=>a+x.charCodeAt(0)*(i+7),0)}
function similarity(a,b){a=a.toUpperCase();b=b.toUpperCase();const aa=new Set([...a].map((_,i)=>a.slice(i,i+2)).filter(x=>x.length===2)),bb=new Set([...b].map((_,i)=>b.slice(i,i+2)).filter(x=>x.length===2));let k=0;aa.forEach(x=>bb.has(x)&&k++);return k/Math.max(1,Math.min(aa.size,bb.size))}
function scoreName(n,b,roots,examples){let s=80;if(n.length>=5&&n.length<=8)s+=7;if(/[AEIOUY]$/.test(n))s+=2;if(/[^AEIOUY]{3,}/.test(n))s-=10;if(new Set(n).size/n.length>.75)s+=3;if(roots.some(r=>n.includes(r)))s+=5;if(examples.length){const mx=Math.max(...examples.map(e=>similarity(n,e)));if(mx>.25&&mx<.75)s+=4;if(mx>=.8)s-=12}for(const bad of avoidList(b))if(n.includes(bad))s-=35;s+=(hash(n)%9)-4;return Math.max(40,Math.min(97,Math.round(s)))}
function generateFromBrief(b,seen,count=50){const roots=rootsFromBrief(b),examples=asciiExamples(b.examples),out=[],bad=avoidList(b);let tries=0;while(out.length<count&&tries++<12000){let n;const mode=Math.random();if(roots.length&&mode<.55){const r=roots[Math.random()*roots.length|0];n=(mode<.2?PFX[Math.random()*PFX.length|0]+r:r+(mode<.38?MID[Math.random()*MID.length|0]:END[Math.random()*END.length|0]))}else if(examples.length&&mode<.78){const e=examples[Math.random()*examples.length|0],cut=Math.max(2,Math.min(e.length-1,2+(Math.random()*3|0)));n=(Math.random()<.5?e.slice(0,cut)+END[Math.random()*END.length|0]:PFX[Math.random()*PFX.length|0]+e.slice(-cut))}else n=PFX[Math.random()*PFX.length|0]+MID[Math.random()*MID.length|0]+END[Math.random()*END.length|0];n=n.toUpperCase().replace(/[^A-Z]/g,'');if(n.length<b.minLength||n.length>b.maxLength||seen.has(n)||bad.some(x=>n.includes(x)))continue;const score=scoreName(n,b,roots,examples);if(score>=86){seen.add(n);out.push({name:n,score,briefMatch:true})}}return out.sort((a,b)=>b.score-a.score)}
async function callBase(path,names,env,ctx,max){const req=new Request(`https://brand-hunter.local${path}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({names:names.slice(0,max)})}),res=await base.fetch(req,env,ctx);if(!res.ok)return[];const j=await res.json();return j.results||[]}
async function screenMany(candidates,env,ctx,limit=10){const chosen=candidates.slice(0,limit),map=new Map;for(let i=0;i<chosen.length;i+=5){const r=await callBase('/api/screen',chosen.slice(i,i+5).map(x=>x.name),env,ctx,5);r.forEach(x=>map.set(x.name,x))}return chosen.map(c=>({...c,screen:map.get(c.name)||null}))}
async function deepMany(candidates,env,ctx,limit=3){const chosen=candidates.slice(0,limit),r=await callBase('/api/knockout',chosen.map(x=>x.name),env,ctx,3),map=new Map(r.map(x=>[x.name,x]));return chosen.map(c=>({...c,knockout:map.get(c.name)||null}))}
async function runUniversalCycle(env,ctx,manual=false){if(!env.AUTOPILOT_KV)return{ok:false,error:'AUTOPILOT_KV not configured'};const brief=await getBrief(env),seen=new Set(JSON.parse(await env.AUTOPILOT_KV.get('universal_seen')||'[]')),batch=generateFromBrief(brief,seen,manual?60:40),screened=await screenMany(batch,env,ctx,manual?12:10),promising=screened.filter(c=>c.screen&&c.score>=88&&c.screen.riskScore<=18&&c.screen.riskLabel!=='RED').slice(0,manual?5:3),deep=await deepMany(promising,env,ctx,3),pass=deep.filter(c=>c.knockout?.decision==='PASS'),gated=[];for(const c of pass)gated.push({...c,legalGate:await legalRiskGate(env,c)});const technical=gated.filter(x=>x.legalGate.status===FINAL_LABEL),review=gated.filter(x=>x.legalGate.status==='LEGAL_REVIEW'),blocked=gated.filter(x=>x.legalGate.status==='BLOCK');if(!manual){await env.AUTOPILOT_KV.put('universal_seen',JSON.stringify([...seen].slice(-20000)));const history=JSON.parse(await env.AUTOPILOT_KV.get('universal_history')||'[]'),cycle={at:new Date().toISOString(),briefTitle:brief.title,generated:batch.length,screened:screened.length,deep:deep.length,technical:technical.map(x=>({name:x.name,score:x.score,legalRisk:x.legalGate.riskScore}))};history.unshift(cycle);await env.AUTOPILOT_KV.put('universal_history',JSON.stringify(history.slice(0,100)));for(const f of technical){const key=`telegram_technical_pass:${f.name}`;if(!await env.AUTOPILOT_KV.get(key)){const sent=await sendTelegram(env,`🛡️ BRAND HUNTER — TECHNICAL PASS\n\n${f.name}\nScore: ${f.score}\nLegal risk: ${f.legalGate.riskScore}\nЗадание: ${brief.title}\n\nКандидат найден по твоему поисковому заданию и прошёл усиленный автоматический фильтр. Перед регистрацией всё равно нужна профессиональная trademark clearance.`);if(sent.ok)await env.AUTOPILOT_KV.put(key,new Date().toISOString())}}}
 return{ok:true,brief,generated:batch.length,results:manual?screened.slice(0,12):undefined,deep:manual?deep:undefined,finalists:technical.map(x=>({name:x.name,score:x.score,status:FINAL_LABEL,legalRisk:x.legalGate.riskScore})),legalReview:review.map(x=>({name:x.name,riskScore:x.legalGate.riskScore,reasons:x.legalGate.reasons})),blocked:blocked.map(x=>({name:x.name,riskScore:x.legalGate.riskScore,reasons:x.legalGate.reasons}))}}
async function handleCustomSearch(request,env,ctx){if(request.method!=='POST')return Response.json({ok:false,error:'POST required'},{status:405,headers:JSON_HEADERS});return Response.json(await runUniversalCycle(env,ctx,true),{headers:JSON_HEADERS})}
async function handleAutopilot(request,env,ctx){if(request.method==='GET'){if(!env.AUTOPILOT_KV)return Response.json({ok:false,status:'SETUP_REQUIRED'},{status:503,headers:JSON_HEADERS});return Response.json({ok:true,status:'READY',brief:await getBrief(env),history:JSON.parse(await env.AUTOPILOT_KV.get('universal_history')||'[]'),legalGateVersion:LEGAL_GATE_VERSION,finalistPolicy:'TECHNICAL_PASS_ONLY'},{headers:JSON_HEADERS})}if(request.method==='POST')return Response.json(await runUniversalCycle(env,ctx,false),{headers:JSON_HEADERS});return Response.json({ok:false,error:'GET or POST required'},{status:405,headers:JSON_HEADERS})}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname.startsWith('/api/brief'))return handleBrief(request,env);if(url.pathname.startsWith('/api/custom-search'))return handleCustomSearch(request,env,ctx);if(url.pathname.startsWith('/api/telegram')||url.pathname.startsWith('/api/notifications'))return handleTelegram(request,env);if(url.pathname.startsWith('/api/autopilot'))return handleAutopilot(request,env,ctx);return base.fetch(request,env,ctx)},async scheduled(controller,env,ctx){ctx?.waitUntil?.(runUniversalCycle(env,ctx,false))}};
