const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"};
function timeoutSignal(ms){return AbortSignal.timeout?AbortSignal.timeout(ms):undefined}
async function fetchText(url,ms=6500,headers={}){try{const r=await fetch(url,{headers,signal:timeoutSignal(ms),redirect:"follow"});if(!r.ok)return{ok:false,status:r.status,text:""};return{ok:true,status:r.status,text:(await r.text()).slice(0,350000)}}catch(e){return{ok:false,status:0,text:"",error:String(e?.message||e)}}}
function ddgQuery(q){return`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`}
async function searchSignal(name,query){const r=await fetchText(ddgQuery(query));if(!r.ok)return{available:false,hits:0,reason:`search unavailable (${r.status||"network"})`};const html=r.text.toLowerCase(),lower=name.toLowerCase(),cards=(html.match(/result__a/g)||[]).length,mentions=Math.max(0,(html.split(lower).length-1)-1),hits=Math.min(12,cards)+Math.min(12,mentions);return{available:true,hits}}
async function appleSignal(name){try{const url=`https://itunes.apple.com/search?term=${encodeURIComponent(name)}&entity=software&limit=25`;const r=await fetch(url,{signal:timeoutSignal(6500)});if(!r.ok)return{available:false,hits:0};const j=await r.json(),n=name.toLowerCase(),exact=(j.results||[]).filter(x=>String(x.trackName||"").toLowerCase()===n||String(x.sellerName||"").toLowerCase().includes(n)).length,near=(j.results||[]).filter(x=>String(x.trackName||"").toLowerCase().includes(n)).length;return{available:true,hits:exact*4+near,exact,near}}catch(e){return{available:false,hits:0}}}
async function domainRegistered(domain){try{const r=await fetch(`https://rdap.org/domain/${encodeURIComponent(domain)}`,{headers:{accept:"application/rdap+json,application/json"},signal:timeoutSignal(5500),redirect:"follow"});if(r.status===404)return{available:true,registered:false};if(r.ok)return{available:true,registered:true}}catch(e){}return{available:false,registered:null}}
async function domainSignals(name){const base=name.toLowerCase(),domains=[`${base}.com`,`${base}.ai`,`${base}.app`],results=await Promise.all(domains.map(async d=>({domain:d,...await domainRegistered(d)}))),registered=results.filter(x=>x.registered===true).length,availableCount=results.filter(x=>x.available).length;return{available:availableCount>0,registered,results}}
function riskFromSignals(s){let points=0,confidence=0;if(s.exact.available){points+=Math.min(28,s.exact.hits*3);confidence++}if(s.health.available){points+=Math.min(34,s.health.hits*4);confidence++}if(s.company.available){points+=Math.min(22,s.company.hits*2);confidence++}if(s.play.available){points+=Math.min(28,s.play.hits*4);confidence++}if(s.apple.available){points+=Math.min(35,s.apple.hits*5);confidence++}if(s.domains.available){points+=Math.min(18,s.domains.registered*6);confidence++}points=Math.min(100,points);let label="UNKNOWN";if(confidence>=2){if(points>=62)label="RED";else if(points>=36)label="ORANGE";else if(points>=15)label="YELLOW";else label="LOW-SIGNAL"}return{points,label,confidence}}
async function screenOne(name){const exactQ=`"${name}"`;const[exact,health,company,play,apple,domains]=await Promise.all([searchSignal(name,exactQ),searchSignal(name,`${exactQ} health AI nutrition wellness fitness app`),searchSignal(name,`${exactQ} company startup software SaaS`),searchSignal(name,`site:play.google.com ${exactQ}`),appleSignal(name),domainSignals(name)]);const signals={exact,health,company,play,apple,domains},risk=riskFromSignals(signals);return{name,riskScore:risk.points,riskLabel:risk.label,confidence:risk.confidence,signals}}
async function handleScreen(request){if(request.method==="OPTIONS")return new Response("",{status:204,headers:{...JSON_HEADERS,"access-control-allow-methods":"POST,GET,OPTIONS","access-control-allow-headers":"content-type"}});if(request.method==="GET")return new Response(JSON.stringify({ok:true,service:"Brand Hunter Cloudflare Screening",mode:"public-signal screening",maxNamesPerRequest:5}),{status:200,headers:JSON_HEADERS});if(request.method!=="POST")return new Response(JSON.stringify({error:"POST required"}),{status:405,headers:JSON_HEADERS});let body;try{body=await request.json()}catch{return new Response(JSON.stringify({error:"invalid JSON"}),{status:400,headers:JSON_HEADERS})}const names=(Array.isArray(body?.names)?body.names:[]).map(x=>String(x||"").trim().toUpperCase()).filter(x=>/^[A-Z0-9]{4,12}$/.test(x)).slice(0,5);if(!names.length)return new Response(JSON.stringify({error:"names[] required"}),{status:400,headers:JSON_HEADERS});const results=await Promise.all(names.map(screenOne));return new Response(JSON.stringify({ok:true,screenedAt:new Date().toISOString(),host:"cloudflare-workers",results}),{status:200,headers:JSON_HEADERS})}
export default {async fetch(request,env){const url=new URL(request.url);if(url.pathname==="/api/screen"||url.pathname==="/api/screen/")return handleScreen(request);return env.ASSETS.fetch(request)}};
