const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","access-control-allow-origin":"*"};
function timeoutSignal(ms){return AbortSignal.timeout?AbortSignal.timeout(ms):undefined}
async function fetchText(url,ms=6500,headers={}){try{const r=await fetch(url,{headers,signal:timeoutSignal(ms),redirect:"follow"});if(!r.ok)return{ok:false,status:r.status,text:""};return{ok:true,status:r.status,text:(await r.text()).slice(0,350000)}}catch(e){return{ok:false,status:0,text:"",error:String(e?.message||e)}}}
function ddgQuery(q){return`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`}
async function searchSignal(name,query){const r=await fetchText(ddgQuery(query));if(!r.ok)return{available:false,hits:0,reason:`search unavailable (${r.status||"network"})`};const html=r.text.toLowerCase(),lower=name.toLowerCase(),cards=(html.match(/result__a/g)||[]).length,mentions=Math.max(0,(html.split(lower).length-1)-1),hits=Math.min(12,cards)+Math.min(12,mentions);return{available:true,hits}}
async function appleSignal(name){try{const r=await fetch(`https://itunes.apple.com/search?term=${encodeURIComponent(name)}&entity=software&limit=25`,{signal:timeoutSignal(6500)});if(!r.ok)return{available:false,hits:0};const j=await r.json(),n=name.toLowerCase(),exact=(j.results||[]).filter(x=>String(x.trackName||'').toLowerCase()===n||String(x.sellerName||'').toLowerCase().includes(n)).length,near=(j.results||[]).filter(x=>String(x.trackName||'').toLowerCase().includes(n)).length;return{available:true,hits:exact*4+near,exact,near}}catch{return{available:false,hits:0}}}
async function domainRegistered(domain){try{const r=await fetch(`https://rdap.org/domain/${encodeURIComponent(domain)}`,{headers:{accept:'application/rdap+json,application/json'},signal:timeoutSignal(5500),redirect:'follow'});if(r.status===404)return{available:true,registered:false};if(r.ok)return{available:true,registered:true}}catch{}return{available:false,registered:null}}
async function domainSignals(name){const base=name.toLowerCase(),domains=[`${base}.com`,`${base}.ai`,`${base}.app`],results=await Promise.all(domains.map(async d=>({domain:d,...await domainRegistered(d)}))),registered=results.filter(x=>x.registered===true).length,availableCount=results.filter(x=>x.available).length;return{available:availableCount>0,registered,results}}
function riskFromSignals(s){let points=0,confidence=0;if(s.exact.available){points+=Math.min(28,s.exact.hits*3);confidence++}if(s.health.available){points+=Math.min(34,s.health.hits*4);confidence++}if(s.company.available){points+=Math.min(22,s.company.hits*2);confidence++}if(s.play.available){points+=Math.min(28,s.play.hits*4);confidence++}if(s.apple.available){points+=Math.min(35,s.apple.hits*5);confidence++}if(s.domains.available){points+=Math.min(18,s.domains.registered*6);confidence++}points=Math.min(100,points);let label='UNKNOWN';if(confidence>=2)label=points>=62?'RED':points>=36?'ORANGE':points>=15?'YELLOW':'LOW-SIGNAL';return{points,label,confidence}}
async function screenOne(name){const q=`"${name}"`,[exact,health,company,play,apple,domains]=await Promise.all([searchSignal(name,q),searchSignal(name,`${q} health AI nutrition wellness fitness app`),searchSignal(name,`${q} company startup software SaaS`),searchSignal(name,`site:play.google.com ${q}`),appleSignal(name),domainSignals(name)]),signals={exact,health,company,play,apple,domains},risk=riskFromSignals(signals);return{name,riskScore:risk.points,riskLabel:risk.label,confidence:risk.confidence,signals}}
async function deepOne(name){const q=`"${name}"`,[base,tmview,euipo,wipo,health,apps,domains]=await Promise.all([screenOne(name),searchSignal(name,`site:tmview.org ${q}`),searchSignal(name,`site:euipo.europa.eu ${q}`),searchSignal(name,`site:wipo.int ${q}`),searchSignal(name,`${q} health wellness nutrition fitness medical AI`),searchSignal(name,`${q} app software mobile`),domainSignals(name)]);let score=base.riskScore;const trademarkHits=[tmview,euipo,wipo].reduce((a,x)=>a+(x.available?x.hits:0),0);score=Math.min(100,score+Math.min(40,trademarkHits*7)+Math.min(18,(health.available?health.hits:0)*3)+Math.min(12,(apps.available?apps.hits:0)*2));const unknown=[tmview,euipo,wipo,health,apps,domains].filter(x=>!x.available).length;let decision='REVIEW';if(score>=65||trademarkHits>=4)decision='BLOCK';else if(score<=18&&unknown===0&&trademarkHits===0)decision='PASS';else if(unknown>=3)decision='UNKNOWN';return{name,decision,deepRisk:score,trademarkHits,unknown,checkedAt:new Date().toISOString(),checks:{publicScreen:base,tmview,euipo,wipo,health,apps,domains},disclaimer:'Automated public-signal knockout only. Not a legal trademark clearance.'}}
async function parseNames(request,max){let body;try{body=await request.json()}catch{return null}return(Array.isArray(body?.names)?body.names:[]).map(x=>String(x||'').trim().toUpperCase()).filter(x=>/^[A-Z0-9]{4,12}$/.test(x)).slice(0,max)}
async function handleScreen(request){if(request.method==='GET')return Response.json({ok:true,service:'Brand Hunter screening',maxNamesPerRequest:5},{headers:JSON_HEADERS});if(request.method!=='POST')return Response.json({error:'POST required'},{status:405,headers:JSON_HEADERS});const names=await parseNames(request,5);if(!names?.length)return Response.json({error:'names[] required'},{status:400,headers:JSON_HEADERS});return Response.json({ok:true,results:await Promise.all(names.map(screenOne))},{headers:JSON_HEADERS})}
async function handleKnockout(request){if(request.method==='GET')return Response.json({ok:true,service:'Brand Hunter deep knockout',maxNamesPerRequest:3,legalClearance:false},{headers:JSON_HEADERS});if(request.method!=='POST')return Response.json({error:'POST required'},{status:405,headers:JSON_HEADERS});const names=await parseNames(request,3);if(!names?.length)return Response.json({error:'names[] required'},{status:400,headers:JSON_HEADERS});return Response.json({ok:true,results:await Promise.all(names.map(deepOne))},{headers:JSON_HEADERS})}
const AP_PREFIX=['AL','AR','AV','EL','EN','ER','EV','IL','IN','IR','LA','LE','LO','MA','ME','MI','NA','NE','NO','OR','RA','RE','SA','SE','TA','TE','VA','VE','VI','VO','SY','LY','AY'];
const AP_MID=['L','M','N','R','S','T','V','D','LOR','REN','VEL','MAR','NEL','RIN','SOR','TAR','VEN','MER','LIS','NOR','VAR','SEL','NEX','LYN','ORA'];
const AP_END=['A','O','I','E','EN','EL','ER','IS','ON','OR','IO','IA','EO','AR','IN','OS','YA'];
const AP_BLOCK=['VITA','VYTA','VIVA','VIDA','VITAVIA','VYTAVIA','MAYSTER','MASTER','NOVA','LUNA','AURA','MIRA'];
function hash(n){return[...n].reduce((a,x,i)=>a+x.charCodeAt(0)*(i+7),0)}
function localScore(n){let s=82;if(n.length>=5&&n.length<=7)s+=7;if(/[AEIOUY]$/.test(n))s+=2;if(/[^AEIOUY]{3,}/.test(n))s-=12;if(AP_BLOCK.some(x=>n.includes(x)))s-=25;const h=hash(n);s+=(h%9)-4;return Math.max(45,Math.min(96,Math.round(s)))}
function generateBatch(seen,count=36){const out=[];let tries=0;while(out.length<count&&tries++<8000){const n=(AP_PREFIX[Math.random()*AP_PREFIX.length|0]+AP_MID[Math.random()*AP_MID.length|0]+AP_END[Math.random()*AP_END.length|0]).toUpperCase();if(n.length<5||n.length>9||seen.has(n)||AP_BLOCK.some(x=>n.includes(x)))continue;const score=localScore(n);if(score>=88){seen.add(n);out.push({name:n,score})}}return out.sort((a,b)=>b.score-a.score)}
function randomTopic(){const a=new Uint8Array(18);crypto.getRandomValues(a);return'brandhunter-'+[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function getNotifyTopic(env,create=false){if(!env.AUTOPILOT_KV)return null;let t=await env.AUTOPILOT_KV.get('notify_topic');if(!t&&create){t=randomTopic();await env.AUTOPILOT_KV.put('notify_topic',t)}return t}
async function sendNtfy(env,title,message){const topic=await getNotifyTopic(env,false);if(!topic)return false;try{const r=await fetch(`https://ntfy.sh/${topic}`,{method:'POST',headers:{'title':title,'priority':'high','tags':'tada,magnifying_glass','click':'https://brand-hunter.maysterww.workers.dev/autopilot.html','content-type':'text/plain; charset=utf-8'},body:message,signal:timeoutSignal(6500)});return r.ok}catch{return false}}
async function sendFinalist(env,candidate){await sendNtfy(env,'Brand Hunter: FINALIST',`${candidate.name} · Score ${candidate.score} · Deep risk ${candidate.knockout?.deepRisk??'—'}`);if(env.AUTOPILOT_WEBHOOK_URL){try{await fetch(env.AUTOPILOT_WEBHOOK_URL,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({event:'brand_hunter_finalist',title:'Brand Hunter нашёл финалиста',candidate}),signal:timeoutSignal(6500)})}catch{}}}
async function handleNotifications(request,env){if(!env.AUTOPILOT_KV)return Response.json({ok:false,error:'AUTOPILOT_KV not configured'},{status:503,headers:JSON_HEADERS});if(request.method==='GET'){const t=await getNotifyTopic(env,false);return Response.json({ok:true,enabled:!!t},{headers:JSON_HEADERS})}if(request.method!=='POST')return Response.json({error:'GET or POST required'},{status:405,headers:JSON_HEADERS});let body={};try{body=await request.json()}catch{}const action=body?.action||'enable';const topic=await getNotifyTopic(env,true);if(action==='test'){const sent=await sendNtfy(env,'Brand Hunter','Тестовое уведомление. Канал финалистов подключён.');return Response.json({ok:sent,enabled:true,topicUrl:`https://ntfy.sh/${topic}`},{headers:JSON_HEADERS})}return Response.json({ok:true,enabled:true,topicUrl:`https://ntfy.sh/${topic}`},{headers:JSON_HEADERS})}
async function autopilotCycle(env){if(!env.AUTOPILOT_KV)return{ok:false,error:'AUTOPILOT_KV not configured'};const seen=new Set(JSON.parse(await env.AUTOPILOT_KV.get('seen')||'[]')),batch=generateBatch(seen,30),short=batch.slice(0,8),screened=await Promise.all(short.map(async c=>({...c,screen:await screenOne(c.name)}))),promising=screened.filter(c=>c.score>=90&&c.screen.riskScore<=18&&c.screen.riskLabel!=='RED').slice(0,3),deep=await Promise.all(promising.map(async c=>({...c,knockout:await deepOne(c.name)}))),finalists=deep.filter(c=>c.score>=90&&c.knockout.decision==='PASS');await env.AUTOPILOT_KV.put('seen',JSON.stringify([...seen].slice(-15000)));const history=JSON.parse(await env.AUTOPILOT_KV.get('history')||'[]'),cycle={at:new Date().toISOString(),generated:batch.length,screened:short.length,deep:deep.length,finalists:finalists.map(x=>({name:x.name,score:x.score,deepRisk:x.knockout.deepRisk}))};history.unshift(cycle);await env.AUTOPILOT_KV.put('history',JSON.stringify(history.slice(0,100)));for(const f of finalists){const key=`finalist:${f.name}`;if(!await env.AUTOPILOT_KV.get(key)){await env.AUTOPILOT_KV.put(key,JSON.stringify(f));await sendFinalist(env,f)}}return{ok:true,cycle,finalists}}
async function handleAutopilot(request,env){if(request.method==='GET'){if(!env.AUTOPILOT_KV)return Response.json({ok:false,status:'SETUP_REQUIRED',missing:['AUTOPILOT_KV'],note:'Create KV namespace and connect binding AUTOPILOT_KV.'},{status:503,headers:JSON_HEADERS});return Response.json({ok:true,status:'READY',history:JSON.parse(await env.AUTOPILOT_KV.get('history')||'[]')},{headers:JSON_HEADERS})}if(request.method==='POST')return Response.json(await autopilotCycle(env),{headers:JSON_HEADERS});return Response.json({error:'GET or POST required'},{status:405,headers:JSON_HEADERS})}
const AUTOPILOT_PANEL=`<section class="lab" id="autopilotPanel"><div class="eyebrow">0.8 AUTOPILOT</div><h2>Автоматический охотник</h2><div class="sub">Сервер сам генерирует, проверяет и отбрасывает имена. Плановый цикл — каждые 4 часа.</div><button id="runAutopilotNow">Запустить AUTOPILOT сейчас</button><div class="stage" id="autopilotStatus">Проверяю состояние…</div><div class="list" id="autopilotHistory"></div></section><script>(()=>{const s=document.getElementById('autopilotStatus'),b=document.getElementById('runAutopilotNow'),h=document.getElementById('autopilotHistory');function render(d){const a=d.history||[];h.innerHTML=a.slice(0,5).map(x=>'<div class="card"><b>'+new Date(x.at).toLocaleString()+'</b><div class="mini">Generated '+x.generated+' · Screened '+x.screened+' · Deep '+x.deep+' · Finalists '+(x.finalists?.length||0)+'</div>'+(x.finalists?.length?'<div class="badge">'+x.finalists.map(f=>f.name).join(', ')+'</div>':'')+'</div>').join('')||'<div class="empty">Циклов пока нет.</div>'}async function load(){try{const r=await fetch('/api/autopilot',{cache:'no-store'}),d=await r.json();s.textContent=d.status==='READY'?'AUTOPILOT READY · каждые 4 часа':'SETUP REQUIRED';render(d)}catch{s.textContent='Не удалось загрузить статус.'}}b.onclick=async()=>{b.disabled=true;s.textContent='Идёт автономный поиск и Deep Knockout…';try{const r=await fetch('/api/autopilot',{method:'POST',cache:'no-store'}),d=await r.json();if(!d.ok)throw 0;s.textContent=d.finalists?.length?'Найден финалист: '+d.finalists.map(x=>x.name).join(', '):'Цикл завершён. Финалистов в этой волне нет.';await load()}catch{s.textContent='Ошибка запуска. Попробуй ещё раз.'}b.disabled=false};load()})();<\/script>`;
async function serveHome(request,env){const r=await env.ASSETS.fetch(request);if(!r.ok)return r;const h=new Headers(r.headers);h.set('content-type','text/html; charset=utf-8');h.set('cache-control','no-store');let html=await r.text();html=html.replace('</head>','<link rel="icon" type="image/svg+xml" href="/brand-hunter-icon.svg"><link rel="apple-touch-icon" href="/brand-hunter-icon.svg"></head>');html=html.replace('</main>',AUTOPILOT_PANEL+'</main>');html=html.replace('0.7.3 PATH INTELLIGENCE','0.8 AUTOPILOT');return new Response(html,{status:r.status,headers:h})}
export default{async fetch(request,env){const url=new URL(request.url);if(url.pathname.startsWith('/api/screen'))return handleScreen(request);if(url.pathname.startsWith('/api/knockout'))return handleKnockout(request);if(url.pathname.startsWith('/api/notifications'))return handleNotifications(request,env);if(url.pathname.startsWith('/api/autopilot'))return handleAutopilot(request,env);if(url.pathname==='/'||url.pathname==='/index.html')return serveHome(request,env);return env.ASSETS.fetch(request)},async scheduled(event,env,ctx){ctx.waitUntil(autopilotCycle(env))}};
